/*
===============================================================================
VALIDATION SCRIPT : BRONZE LAYER
===============================================================================
Script Purpose:
    This script checks for various data discrepancies within the sources. 
	The results from these scripts helps rectify the data impurities and 
	help create accurate SILVER layer downstream. 

===============================================================================
*/
SELECT * FROM CRM_CUST_INFO;

-- Checking for NULLs and duplicates in PK
-- Expectation : No result 
SELECT COUNT(*), COUNT(DISTINCT CST_KEY) FROM CRM_CUST_INFO; 

SELECT CST_ID, COUNT(*) FROM CRM_CUST_INFO GROUP BY CST_ID HAVING COUNT(*)>1 OR CST_ID IS NULL; 

SELECT CST_KEY, COUNT(*) FROM CRM_CUST_INFO GROUP BY CST_KEY HAVING COUNT(*)>1 OR CST_KEY IS NULL; 

-- Check for unwanted spaces 
-- Expectation : No resutls 

SELECT CST_FIRSTNAME FROM BRONZE.CRM_CUST_INFO WHERE CST_FIRSTNAME != TRIM(CST_FIRSTNAME);
SELECT CST_LASTNAME FROM BRONZE.CRM_CUST_INFO WHERE CST_LASTNAME != TRIM(CST_LASTNAME);

-- Data standardization and consistency check 
SELECT DISTINCT CST_GNDR, COUNT(*) FROM BRONZE.CRM_CUST_INFO GROUP BY 1;


/***********************/

SELECT * FROM CRM_PROD_INFO;


-- Checking for NULLs and duplicates in PK
-- Expectation : No result 
SELECT COUNT(*), COUNT(DISTINCT PRD_ID) FROM CRM_PROD_INFO; 

SELECT PRD_ID, COUNT(*) FROM CRM_PROD_INFO GROUP BY PRD_ID HAVING COUNT(*)>1 OR PRD_ID IS NULL; 


-- Check for unwanted spaces 
-- Expectation : No resutls
SELECT PRD_NM FROM BRONZE.CRM_PROD_INFO WHERE TRIM(PRD_NM) != PRD_NM;


-- Check for NULLS or negative numbers 
-- Expectation : No resutls
SELECT PRD_COST FROM BRONZE.CRM_PROD_INFO
WHERE PRD_COST <=0 OR PRD_COST IS NULL;

-- Data standardization and consistency check 
SELECT DISTINCT PRD_LINE FROM BRONZE.CRM_PROD_INFO
;

-- Check for invaid order dates 
SELECT * FROM BRONZE.CRM_PROD_INFO WHERE PRD_END_DT<PRD_START_DT;


/***********************/

SELECT * FROM CRM_SALES_DETAIL_INFO;

SELECT * 
FROM CRM_SALES_DETAIL_INFO
WHERE SLS_ORDER_DT<=0 
OR LENGTH(SLS_ORDER_DT)!=8
OR SLS_ORDER_DT>TO_CHAR(CURRENT_DATE,'YYYYMMDD')
; 

SELECT * 
FROM CRM_SALES_DETAIL_INFO
WHERE SLS_SHIP_DT<=0;
;

SELECT * 
FROM CRM_SALES_DETAIL_INFO
WHERE SLS_DUE_DT<=0;
;

SELECT * 
FROM CRM_SALES_DETAIL_INFO
WHERE SLS_ORDER_DT > SLS_SHIP_DT
OR SLS_ORDER_DT > SLS_DUE_DT
;


-- SALES = QUANTITY * PRICE 
-- Expected outcome : No result 

SELECT * 
FROM CRM_SALES_DETAIL_INFO
WHERE SLS_SALES != SLS_QUANTITY * SLS_PRICE
OR SLS_SALES <= 0 OR SLS_QUANTITY<=0 OR SLS_PRICE<=0
OR SLS_SALES IS NULL OR SLS_QUANTITY IS NULL OR SLS_PRICE IS NULL 
;





/***********************/



SELECT * FROM ERP_CUST_AZ12_INFO;

SELECT GEN, COUNT(*) FROM ERP_CUST_AZ12_INFO GROUP BY 1;

SELECT DISTINCT 
    GEN ,
    CASE WHEN UPPER(TRIM(GEN)) IN ('M', 'MALE') THEN 'MALE'
         WHEN UPPER(TRIM(GEN)) IN ('F', 'FEMALE') THEN 'FEMALE'
        ELSE 'NOT AVAILABLE'
    END AS GEN_NEW     
FROM ERP_CUST_AZ12_INFO 
;


SELECT * FROM ERP_CUST_AZ12_INFO
WHERE GEN IN ('F','M','M', 'F' )
;

SELECT * FROM ERP_CUST_AZ12_INFO
WHERE BDATE > CURRENT_DATE
OR BDATE < '1950-01-01'
OR LENGTH(BDATE) < 10
;


/***********************/

SELECT * FROM ERP_LOC_A101_INFO;

SELECT DISTINCT CNTRY FROM ERP_LOC_A101_INFO
ORDER BY CNTRY
;

SELECT DISTINCT CNTRY FROM ERP_LOC_A101_INFO
WHERE LENGTH(CNTRY) <=3
;

SELECT COUNT(*), COUNT(DISTINCT CID) FROM ERP_LOC_A101_INFO
;

SELECT 
    CNTRY,
    (SELECT COUNTRY_NAME FROM REF_COUNTRY_CD B WHERE A.CNTRY = B.COUNTRY_CD)
FROM ERP_LOC_A101_INFO A
WHERE CNTRY IN (SELECT COUNTRY_CD FROM REF_COUNTRY_CD)
;

/***********************/

SELECT * FROM ERP_PX_CAT_G1V2_INFO;

SELECT COUNT(*), COUNT(DISTINCT ID) FROM ERP_PX_CAT_G1V2_INFO;


SELECT DISTINCT CAT FROM ERP_PX_CAT_G1V2_INFO;
SELECT * FROM ERP_PX_CAT_G1V2_INFO WHERE CAT != TRIM(CAT);

SELECT DISTINCT SUBCAT FROM ERP_PX_CAT_G1V2_INFO;
SELECT * FROM ERP_PX_CAT_G1V2_INFO WHERE SUBCAT != TRIM(SUBCAT);

SELECT DISTINCT MAINTENANCE FROM ERP_PX_CAT_G1V2_INFO;
SELECT * FROM ERP_PX_CAT_G1V2_INFO WHERE MAINTENANCE != TRIM(MAINTENANCE);

/***********************/

SELECT * FROM REF_COUNTRY_CD;

SELECT COUNTRY_CD, COUNT(DISTINCT COUNTRY_NAME) 
FROM REF_COUNTRY_CD
GROUP BY 1 
;


