/*
===============================================================================
DDL Script: Create Gold Views
===============================================================================
Script Purpose:
    This script creates views for the Gold layer in the data warehouse. 
    The Gold layer represents the final dimension and fact tables (Star Schema)

    Each view performs transformations and combines data from the Silver layer 
    to produce a clean, enriched, and business-ready dataset.

Usage:
    - These views can be queried directly for analytics and reporting.
===============================================================================
*/

-- =============================================================================
-- Create Dimension: GOLD.DIM_CUSTOMERS
-- =============================================================================

USE ROLE DWH_ENG; 
USE EDW; 
USE SCHEMA GOLD;

CREATE OR REPLACE VIEW DIM_CUSTOMER AS
SELECT
    ROW_NUMBER() OVER (ORDER BY CI.CST_ID) AS CUSTOMER_KEY,
    CI.CST_ID AS CUSTOMER_ID, 
    CI.CST_KEY AS CUSTOMER_NUMBER, 
    CI.CST_FIRSTNAME AS FIRST_NAME, 
    CI.CST_LASTNAME AS LAST_NAME, 
    LOC.CNTRY AS COUNTRY, 
    CI.CST_MARITAL_STATUS AS MARITAL_STATUS, 
    CASE WHEN CI.CST_GNDR != 'NOT AVAILABLE' THEN CI.CST_GNDR -- CRM IS MASTER SOURCE
         ELSE NVL(ERP_CUST.GEN, 'NOT AVAILABLE')
    END AS GENDER,
    ERP_CUST.BDATE AS DATE_OF_BIRTH, 
    CI.CST_CREATE_DATE AS CREATE_DATE
FROM SILVER.CRM_CUST_INFO CI
LEFT JOIN SILVER.ERP_CUST_AZ12_INFO ERP_CUST 
    ON CI.CST_KEY = ERP_CUST.CID
LEFT JOIN SILVER.ERP_LOC_A101_INFO LOC 
    ON CI.CST_KEY = LOC.CID
;


-- =============================================================================
-- Create Dimension: GOLD.DIM_PRODUCTS
-- =============================================================================
CREATE OR REPLACE VIEW DIM_PRODUCT AS
SELECT
    ROW_NUMBER() OVER (ORDER BY PRD.PRD_START_DT, PRD.PRD_KEY) AS PRODUCT_KEY,
    PRD.PRD_ID AS PRODUCT_ID, 
    PRD.PRD_KEY AS PRODUCT_NUMBER, 
    PRD.PRD_NM AS PRODUCT_NAME, 
    PRD.CAT_ID AS CATEGORY_ID,
    CAT.CAT AS CATEGORY,
    CAT.SUBCAT AS SUB_CATEGORY,
    CAT.MAINTENANCE AS MAINTENANCE, 
    PRD.PRD_COST AS PRODUCT_COST, 
    PRD.PRD_LINE AS PRODUCT_LINE, 
    PRD.PRD_START_DT AS PRODUCT_START_DATE
FROM SILVER.CRM_PROD_INFO PRD
LEFT JOIN SILVER.ERP_PX_CAT_G1V2_INFO CAT 
    ON PRD.CAT_ID = CAT.ID
WHERE PRD.PRD_END_DT IS NULL  -- FILTER OUT HISTORICAL DATA 
;


-- =============================================================================
-- Create Fact Table: GOLD.FACT_SALES
-- =============================================================================
CREATE OR REPLACE VIEW FACT_SALES AS
SELECT 
    SALE.SLS_ORD_NUM AS ORDER_NUMBER, 
    PRD.PRODUCT_KEY AS PRODUCT_KEY,         -- SURROGATE KEY GENERATED BY OUR SYSTEM TO CONNECT MULTIPLE DIMs WITH FACT
    CUST.CUSTOMER_KEY AS CUSTOMER_KEY,      -- SURROGATE KEY GENERATED BY OUR SYSTEM TO CONNECT MULTIPLE DIMs WITH FACT 
    SALE.SLS_ORDER_DT AS ORDER_DATE, 
    SALE.SLS_SHIP_DT AS SHIPPING_DATE, 
    SALE.SLS_DUE_DT AS DUE_DATE, 
    SALE.SLS_SALES AS SALES_AMOUNT, 
    SALE.SLS_QUANTITY AS QUANTITY, 
    SALE.SLS_PRICE AS PRICE
FROM SILVER.CRM_SALES_DETAIL_INFO SALE
LEFT JOIN GOLD.DIM_PRODUCT PRD 
    ON SALE.SLS_PRD_KEY = PRD.PRODUCT_NUMBER  
LEFT JOIN GOLD.DIM_CUSTOMER CUST 
    ON SALE.SLS_CUST_ID = CUST.CUSTOMER_ID
;
