/*
===============================================================================
Stored Procedure: Load Silver Layer (Bronze -> Silver)
===============================================================================
Script Purpose:
    This stored procedure performs the ETL (Extract, Transform, Load) process to 
    populate the 'silver' schema tables from the 'bronze' schema.
	Actions Performed:
		- Truncates Silver tables.
		- Inserts transformed and cleansed data from Bronze into Silver tables.
		
Parameters:
    None. 
	  This stored procedure does not accept any parameters or return any values.

Usage Example:
    EXEC Silver.load_silver;
===============================================================================	
*/

USE DWH_ENG;
USE EDW; 
USE SCHEMA SILVER;

CREATE OR REPLACE PROCEDURE SP_LOAD_SILVER()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
		
	TRUNCATE TABLE SILVER.CRM_CUST_INFO ;
	
	INSERT INTO SILVER.CRM_CUST_INFO 
	(CST_ID, CST_KEY, CST_FIRSTNAME, CST_LASTNAME, CST_MARITAL_STATUS, CST_GNDR, CST_CREATE_DATE)
	SELECT 
		CST_ID, 
		CST_KEY, 
		TRIM(CST_FIRSTNAME) AS CST_FIRSTNAME, 
		TRIM(CST_LASTNAME) AS CST_LASTNAME, 
		CASE WHEN UPPER(TRIM(CST_MARITAL_STATUS)) = 'S' THEN 'SINGLE'
			WHEN UPPER(TRIM(CST_MARITAL_STATUS)) = 'M' THEN 'MARRIED'
			ELSE 'NOT AVAILABLE'
		END CST_MARITAL_STATUS, 
		CASE WHEN UPPER(TRIM(CST_GNDR)) = 'F' THEN 'FEMALE'
			WHEN UPPER(TRIM(CST_GNDR)) = 'M' THEN 'MALE'
			ELSE 'NOT AVAILABLE'
		END AS CST_GNDR,     
		CST_CREATE_DATE
	FROM
	(
		SELECT 
			*,
			ROW_NUMBER() OVER (PARTITION BY CST_ID ORDER BY CST_CREATE_DATE) AS RNK
		FROM BRONZE.CRM_CUST_INFO
		WHERE CST_ID IS NOT NULL
	)
	WHERE RNK=1
	;
	
	/********************************/
	
	TRUNCATE TABLE SILVER.CRM_PROD_INFO;
	
	INSERT INTO SILVER.CRM_PROD_INFO 
	(PRD_ID, CAT_ID, PRD_KEY, PRD_NM, PRD_COST, PRD_LINE, PRD_START_DT, PRD_END_DT)
	SELECT 
		PRD_ID,
		REPLACE(SUBSTR(PRD_KEY,1,5),'-','_') AS CAT_ID,
		SUBSTR(PRD_KEY,7,LENGTH(PRD_KEY)) AS PRD_KEY,
		PRD_NM, 
		NVL(PRD_COST,0) AS PRD_COST, 
		CASE UPPER(TRIM(PRD_LINE)) 
			WHEN 'M' THEN 'MOUNTAIN'
			WHEN 'T' THEN 'TOURING'
			WHEN 'R' THEN 'ROAD'
			WHEN 'S' THEN 'OTHER SALES'
			ELSE 'NOT AVAILABLE'
		END AS PRD_LINE, 
		DATE(PRD_START_DT),
		DATE(LEAD(PRD_START_DT) OVER(PARTITION BY PRD_KEY ORDER BY PRD_START_DT))-1 AS PRD_END_DT, 
	FROM BRONZE.CRM_PROD_INFO
	;
	
	/********************************/
	
	TRUNCATE TABLE SILVER.CRM_SALES_DETAIL_INFO ;
	
	INSERT INTO SILVER.CRM_SALES_DETAIL_INFO 
	(
		SLS_ORD_NUM, 
		SLS_PRD_KEY, 
		SLS_CUST_ID, 
		SLS_ORDER_DT, 
		SLS_SHIP_DT, 
		SLS_DUE_DT, 
		SLS_SALES, 
		SLS_QUANTITY, 
		SLS_PRICE
	)
	SELECT 
		SLS_ORD_NUM, 
		SLS_PRD_KEY, 
		SLS_CUST_ID, 
		CASE WHEN SLS_ORDER_DT<=0 OR LENGTH(SLS_ORDER_DT)!=8 THEN NULL 
			ELSE TO_DATE(TO_CHAR(SLS_ORDER_DT))
		END AS SLS_ORDER_DT, 
		CASE WHEN SLS_SHIP_DT<=0 OR LENGTH(SLS_SHIP_DT)!=8 THEN NULL 
			ELSE TO_DATE(TO_CHAR(SLS_SHIP_DT))
		END AS SLS_SHIP_DT, 
		CASE WHEN SLS_DUE_DT<=0 OR LENGTH(SLS_DUE_DT)!=8 THEN NULL 
			ELSE TO_DATE(TO_CHAR(SLS_DUE_DT))
		END AS SLS_DUE_DT,
		CASE WHEN SLS_SALES<=0 OR SLS_SALES IS NULL OR SLS_SALES != SLS_QUANTITY * ABS(SLS_PRICE) THEN SLS_QUANTITY * ABS(SLS_PRICE)
			ELSE SLS_SALES
		END AS SLS_SALES, 
		SLS_QUANTITY,
		CASE WHEN SLS_PRICE <=0 OR SLS_PRICE IS NULL THEN SLS_SALES / NULLIF(SLS_QUANTITY,0) 
			ELSE SLS_PRICE
		END AS SLS_PRICE   
	FROM BRONZE.CRM_SALES_DETAIL_INFO
	;
	
	/********************************/
	
	TRUNCATE TABLE SILVER.ERP_CUST_AZ12_INFO;
	
	INSERT INTO SILVER.ERP_CUST_AZ12_INFO
	(
		CID, 
		BDATE, 
		GEN
	)
	SELECT 
		CASE WHEN CID LIKE 'NAS%' THEN SUBSTR(CID,4, LENGTH(CID))
			ELSE CID
		END AS CID, 
		CASE WHEN BDATE > CURRENT_DATE OR LENGTH(BDATE) < 10 THEN NULL
			ELSE BDATE
		END AS BDATE, 
		CASE WHEN UPPER(TRIM(GEN)) IN ('M', 'MALE') THEN 'MALE'
			WHEN UPPER(TRIM(GEN)) IN ('F', 'FEMALE') THEN 'FEMALE'
			ELSE 'NOT AVAILABLE'
		END AS GEN_NEW     
	FROM BRONZE.ERP_CUST_AZ12_INFO
	;	
	
	/********************************/
	
	TRUNCATE TABLE SILVER.ERP_LOC_A101_INFO;
	
	INSERT INTO SILVER.ERP_LOC_A101_INFO
	(CID, CNTRY)
	SELECT 
		REPLACE(CID,'-','') AS CID, 
		CASE WHEN CNTRY = 'DE' THEN 'Germany'
			WHEN CNTRY IN ('US', 'USA') THEN 'United States'
			WHEN CNTRY IS NULL OR CNTRY ='' THEN 'NOT AVAILABLE'
			ELSE CNTRY
		END AS CNTRY
	FROM BRONZE.ERP_LOC_A101_INFO
	;	
	
	/********************************/
	
	TRUNCATE TABLE SILVER.ERP_PX_CAT_G1V2_INFO;
	
	INSERT INTO SILVER.ERP_PX_CAT_G1V2_INFO
	(
		ID, 
		CAT, 
		SUBCAT, 
		MAINTENANCE
	)
	SELECT  
		ID, 
		CAT, 
		SUBCAT, 
		MAINTENANCE
	FROM BRONZE.ERP_PX_CAT_G1V2_INFO;	
	
	/********************************/

    RETURN 'Procedure executed successfully – SILVER layer table loaded.';

END;
$$;

